Repository Stickerifier/Stickerify, pull requests merged in 2023-10, with the labels that each got.

#155 Updated to Java 21
  .dockerignore
  .github/workflows/unit-test.yml
  Dockerfile
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  qodana.yaml
  src/main/java/com/github/stickerifier/stickerify/process/PathLocator.java
  src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java
Labels: hacktoberfest-accepted

#160 Add failure description when a request fails being sent
  src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java
  src/main/java/com/github/stickerifier/stickerify/telegram/exception/TelegramApiException.java
Labels: enhancement

#162 General performance improvements
  .gitattributes
  Dockerfile
  Railway.dockerfile
  gradlew.bat
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
Labels: enhancement, hacktoberfest-accepted

#164 fixed animation framerate to atmost 60
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
  src/test/resources/low_fps_animated_sticker.tgs
Labels: hacktoberfest-accepted

#170 Use jlink to create a smaller docker image
  .dockerignore
  Dockerfile
  build.gradle
  gradle/libs.versions.toml
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/test/java/com/github/stickerifier/stickerify/ResourceHelper.java
Labels: enhancement, hacktoberfest-accepted, docker

#171 Send usage message when a user starts the bot
  README.md
  src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramRequest.java
  src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java
Labels: documentation, enhancement, unit test, hacktoberfest-accepted
