Repository Stickerifier/Stickerify, pull requests merged in 2023-05, with the labels that each got.

#104 Rework supported formats checks
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
Labels: enhancement

#107 Migrate the project to Java Telegram Bot API
  README.md
  build.gradle
  gradle/libs.versions.toml
  src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java
  src/main/java/com/github/stickerifier/stickerify/logger/StackTraceCleaner.java
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/main/java/com/github/stickerifier/stickerify/runner/Main.java
  src/main/java/com/github/stickerifier/stickerify/telegram/exception/TelegramApiException.java
  src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramRequest.java
  src/main/resources/logback.xml
  src/test/java/com/github/stickerifier/stickerify/logger/LoggingEvent.java
  src/test/java/com/github/stickerifier/stickerify/logger/StackTraceCleanerTest.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
Labels: enhancement, dependencies

#108 Changed timeouts to avoid 429 response
  settings.gradle
  src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
Labels: bug, enhancement, logs

#111 Enforce editor configuration
  .dockerignore
  .editorconfig
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement
