Repository Stickerifier/Stickerify, pull requests merged in 2023-06, with the labels that each got.

#115 Support animated sticker validation
  README.md
  build.gradle
  gradle/libs.versions.toml
  src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java
  src/main/java/com/github/stickerifier/stickerify/media/MediaConstraints.java
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/main/java/com/github/stickerifier/stickerify/runner/Main.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
  src/test/resources/animated_sticker.gz
  src/test/resources/unsupported_archive.gz
Labels: bug, documentation, enhancement, dependencies

#116 Added integration tests
  build.gradle
  gradle/libs.versions.toml
  src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java
  src/test/java/com/github/stickerifier/stickerify/ResourceHelper.java
  src/test/java/com/github/stickerifier/stickerify/bot/MockResponses.java
  src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
Labels: enhancement, unit test, dependencies

#119 Use local FFmpeg instead of Jave's
  gradle/libs.versions.toml
  src/main/java/com/github/stickerifier/stickerify/logger/SubstringHighlighter.java
  src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java
  src/main/java/com/github/stickerifier/stickerify/process/PathLocator.java
  src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java
  src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java
Labels: bug, enhancement, dependencies
